name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - pip=23.1.2 
  - numpy=1.21.6
  - scikit-learn==1.1.2
  - scipy
  - pandas>=1.1,<1.2
  - pip:
    - inference-schema[numpy-support]==1.3.0
    - mlflow
    - azureml-mlflow==1.50.0
    - psutil==5.9.0
    - tqdm
    - ipykernel
    - matplotlib
    - tensorflow==2.12
    - keras-tuner==1.1.3