services:
  backend:
    build: backend/
    ports: 
      - "80:80"
    volumes:
      - ./backend:/app/backend
    networks:
      - deploy_network
    container_name: backend

  frontend:
    build: frontend/
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend    
    ports: 
        - "8501:8501"
    networks:
      - deploy_network
    container_name: frontend

networks:
  deploy_network:
    driver: bridge
