apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: usapp
        image: aschultzdata/usapp:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000
